# Generated by Django 3.1.5 on 2021-01-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='hairolor',
            new_name='haircolor',
        ),
    ]
