# Generated by Django 3.1.5 on 2021-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20210127_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='isOccupied',
            field=models.BooleanField(default=False),
        ),
    ]
